name: Webapp build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.09]

    steps:
      # Vérification du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuration de Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Installation des dépendances avec npm clean-install
      - name: Install dependencies
        run: npm clean-install

      # Linter
      - name: Lint
        run: npm run lint

      # Tests
      - name: Test
        run: npm run test:ci

      # Build
      - name: Build
        run: npm run build
