name: Webapp build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20.18.3
      NPM_VERSION: 10.8.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install exact npm version
        run: |
          npm install -g npm@${{ env.NPM_VERSION }}
          npm config set audit-level high
          npm config set fund false
          npm config set engine-strict true

      - name: Clean environment
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: |
          npm install --strict-peer-deps --legacy-peer-deps
          npx npm-force-resolutions

      - name: Verify critical packages
        run: |
          echo "npm-package-arg version:"
          npm list npm-package-arg
          echo "\nsemver version:"
          npm list semver
          echo "\nIntegrity checks:"
          shasum node_modules/npm-package-arg/package.json
          shasum node_modules/semver/package.json

      - name: Audit Signatures
        run: npm audit signatures --omit=dev

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build